# Secret Scanning Configuration
# This file excludes intentional training secrets from GitHub Secret Scanning
# The ContosoOrderProcessor project contains intentional security vulnerabilities
# for educational purposes to teach developers about resolving security alerts

#paths-ignore:
  # Exclude all ContosoOrderProcessor source code files containing intentional secrets
  # - "ContosoOrderProcessor/**"
  
  # Exclude documentation files that reference the intentional secrets
  #- "EXPOSED_SECRETS_REFERENCE.md"
  #- "README.md"
  #- "PROJECT_SUMMARY.md"
